### ISSUE TITLE
It keeps giving me the error -C -U -M -P not typed even though i did

### ISSUE THREAD

**Issue by Faizan2k7** [vic1707/AutoPlay-PokeMeow-Discord#1]
**Describe the bug**
bot.py: error: the following arguments are required: -C, -U, -M, -P

**Screenshots**
Will need a discord screenshot with the messages concerned by your issue.
Will need the output from the bot in case of an error. (I don't need everything, at least all the error message and maybe the 3/5 last outputs of the program).

**Desktop (please complete the following information):**
 - OS: Windows[e.g. Windows]
 - Browser Chrome[e.g. chrome, safari]

**Additional context**

**Comment by Faizan2k7** [comment]
bot.py: error: the following arguments are required: -C, -U, -M, -P

**Comment by vic1707** [comment]
Can you give me the command you used ? (hide your mail pseudo channel and password)

**Comment by Faizan2k7** [comment]
> Can you give me the command you used ? (hide your mail pseudo channel and password)

![Screenshot 2021-03-13 114103 (1)](https://user-images.githubusercontent.com/80348254/111024785-a562ba80-83f1-11eb-8379-ff984f4db39f.png)

**Comment by vic1707** [comment]
You're not supposed to edit the code to set those flags (or at least not like this ^^').
Restaure the script to it's lastest version and simply execute a command from CMD or a Terminal 
and type something like : 
`python bot.py -U 'John Doe' -M 'johndoe@gmail.com' -P 'mySuperPassword1234' -C 'CHANNEL LINK' ` 
and every other flag needed for your use case.

**Comment by Faizan2k7** [comment]
k thnx
