### ISSUE TITLE
Bot is typing backwards

### ISSUE THREAD

**Issue by pokefan2** [vic1707/AutoPlay-PokeMeow-Discord#10]
I have been trying everything, a direct link to a channel, a link from a browser, but nothing works for me and it keeps saying my url is in wrong/not valid. I am using firefox

**Comment by vic1707** [comment]
Can you show me the shape of your command as well as the shape of your link please ?
With that small amount of informations it's hard to help 😅.

Did you try by putting it between quotes?

**Comment by pokefan2** [comment]
python bot.py -U 'username' -M 'email' -P 'pass' -C 'https://discord.com/channels/84438028703406XXXX/844398523839XXXXXX'

This is what my command is. I put x in place of other numbers

**Comment by vic1707** [comment]
can you try with this quotes : `"` ? 
Also can you send the error thrown by the script please ?

**Comment by pokefan2** [comment]
python bot.py -U 'nickname' -M 'user' -P 'pass!' -C ''https://discord.com/channels/8443802870xxxxxxx/''
It's 16:00:40, working time !
Traceback (most recent call last):
  File "C:\Users\User1\Desktop\AutoPlay-PokeMeow-Discord-main\bot.py", line 38, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "C:\Users\User1\Desktop\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 70, in __init__
    self.DiscordLogin(self.CHANNEL)
  File "C:\Users\User1\Desktop\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 75, in DiscordLogin
    self.get(CHANNEL)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User1\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Malformed URL: URL constructor: ''https://discord.com/channels/844380287034065008/'' is not a valid URL.

And then this is where the script stops. the " didnt work also.

**Comment by vic1707** [comment]
Humm....
first I think the URL is wrong, at least I have one like : 
https://discord.com/channels/7014772084386XXXXX/7064400266023XXXXX
with two times different numbers.

The channel link when pasted in your browser should redirect you directly to the channel (if you're logged in).

**Comment by pokefan2** [comment]
I have tried both. One with only the first set of numbers and also like the example you gave me. When Firefox opens up from the script it doesn’t go to discord even

**Comment by pokefan2** [comment]
I restarted my computer and typed in the script again and now it is able to go onto my Firefox. But now when the script types commands they're backwards? Like checklist is tsilkcehc;  and daily is  yliad;

**Comment by vic1707** [comment]
Wait What ?! how is that even possible !?
Maybe try updating the geckodriver file with the last version : https://github.com/mozilla/geckodriver/releases
If that doesn't work I'll have to admit I have no idea...

**Comment by pokefan2** [comment]
![Capture](https://user-images.githubusercontent.com/84428430/119236851-72722c80-baee-11eb-983f-d0030b974f07.PNG)

this is what happens. I also updated gecko but still nothing.

this is what i've been running in command promt:   python bot.py -C "https://discord.com/channels/844380287034XXXXXX/844398523839XXXXXX" -U anotherxd -M XXXX@gmail.com -P XXXXX 

Nothing in the files have been edited, just straight from download and unzip.

**Comment by vic1707** [comment]
Well, just tried on my machine and it does the same to me too....
No idea why, maybe a discord protection ? 
Can you try on other browser (in case of a Mozilla bug ?

**Comment by vic1707** [comment]
I added a workaround that seems to be working with the last commit 199ab5c . 
Try it out, should work until I find why it's typing backwards...

**Comment by pokefan2** [comment]
Thank  you so much for all you do, that works for now.

**Comment by Aashu-12** [comment]
the bot was typing bakcwards due to some new update of mozzila when i downdated my mozzila version it started to work good again

**Comment by vic1707** [comment]
thanks for th eupdate, i'll leave the option there in case it happens again ^^
