### ISSUE TITLE
Issues getting the bot to properly run

### ISSUE THREAD

**Issue by wreythe** [vic1707/AutoPlay-PokeMeow-Discord#16]
**Describe the bug**
I managed to close out of my discord application, and allow the script to open firefox naturally. but it gets stuck at the "What would you like to be called" screen and doesn't ever pass it. I noticed that the log says something about arguments and I am brand new to Python, selenium, and the entirety of this project. Could I get some help with some more steps on fixing this? I cloned the repo and made sure to install using the proper command. I get firefox to open and push to my discord link, but that is where it ends.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox and Chrome

**Additional context**
I tried using my main account and a brand new account. Nothing works.

**Comment by vic1707** [comment]
I don't know what is the "What would you like to be called" screen.
To use the bot you have to provide it with an existing account.

**Comment by wreythe** [comment]
It is the screen where it tries to accept an invite to the server channel. for some reason the bot opens a blank tab window on firefox that doesn't have the account already logged in on discord. I am not sure how to change or fix that. But it acts as if it needs to create a new account each time. I have been providing the bot an existing account. Do you by chance have a discord available for us to talk? I could easily walk you through all i do live and that might help. Plus I would love to properly learn to run this.

**Comment by vic1707** [comment]
You'll have to provide all of the following arguments `-U` / `-C` / `-M` / `-P`.
The command will look like this (with only those 4 arguments).
`python bot.py -U 'vic1707' -P 'MySuperSecretPassword' -M 'johnDoe@gmail.com' -C 'https://discord.com/channels/1234/1234'`

**Comment by wreythe** [comment]
Do I need to modify that info in the bot.py file? Or just provide -U -C -M -P in the CMD? because I have been providing that info and it doesn't work.

**Comment by vic1707** [comment]
Your firefox browser where you're logged in and the one used by the scripts are differents : no access to the history nor extensions nor passwords ^^



> Do I need to modify that info in the bot.py file? Or just provide -U -C -M -P in the CMD? because I have been providing that info and it doesn't work.

in the command like the one I sent a fex seconds ago.

**Comment by wreythe** [comment]
I have done exactly as you sent and it won't work. I will try again right now and let you know with a screenshot what I see.

**Comment by vic1707** [comment]
a screenshot would be great, it seems like you're not using the headless mod so you should be able to see if the bot logs in entirely.
also, getting a screen to accept the invitation isn't right, you should already be in the server and provide the direct link to the channel.

As for a direct voice call it's not really a problem if you're ok with a not perfect nor very fluent english (I'm french ^^)

**Comment by wreythe** [comment]
The language barrier is fine by me. I am fluent in English and Hebrew and studied French and Spanish for a few years (Even though I am far from fluent or fully understanding of those languages)

**Comment by vic1707** [comment]
okay, no problem then, my discord tag : vic1707#6766
