### ISSUE TITLE
Bot has trouble sending the message

### ISSUE THREAD

**Issue by Gallente-venture** [vic1707/AutoPlay-PokeMeow-Discord#18]
**Describe the bug**
the bot is able to log in correctly but it looked like it was having trouble sending the message, so then it would repeat the action 5 times. 
![Checklist issue](https://user-images.githubusercontent.com/88209912/127747698-4cf2cfba-0909-4ede-9b06-6da645a9b9bb.png)

On my terminal-
It's 12:12:38, working time !
                         fore trying again this action.
                         fore trying again this action.
                         fore trying again this action.
                         fore trying again this action.
MAX RECURSION REACHED
Press Enter to close !!

but it had no problem sending the messages if the -BACKWARDS was not there.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser- Firefox

**Comment by Gallente-venture** [comment]
hmm, I was trying to figure out what's been happening on my end and I think it may just be an issue with input delay. where just the message is typed much faster than it could send a message.

**Comment by vic1707** [comment]
If the bot is typing correctly without the `-BACKWARDS` flag, just remove it from the execution line, no?
That flag is here in case the bot is typing backwards under normal circumstances, by default it shouldn't be set

**Comment by Gallente-venture** [comment]
oh that was me trying it out. If you look at the chat box under the backwards typing you see the ;checklist;checklist;checklist;checklist and yep it was caused by an input delay where it took 2 'Enters' to send a message. But I think thats just an issue on my side, so you are all good.

**Comment by vic1707** [comment]
👌
