### ISSUE TITLE
Bot only checks inventory and checklist.

### ISSUE THREAD

**Issue by SoundWave-2O6** [vic1707/AutoPlay-PokeMeow-Discord#19]
I'm able to run the bot in Chrome (tried Opera but it couldn't get to the login screen)
The bot checks my checklist and does any remaining tasks (double checks quests for some reason) and proceeds to check my inventory for lb and consumables, wich it uses, but closes the tab afterwords.

![image](https://user-images.githubusercontent.com/88780209/129030377-e0566467-cdef-40e2-b759-45c499e7fe65.png)

This is the whole cmd for running the bot.

 - OS: Windows 10
 - Browser: Chrome (as Opera wouldn't work)

I start up the program using a .bat file that automatically inputs the command so I don't have to copy paste it every time I want to start/stop the script.

![image](https://user-images.githubusercontent.com/88780209/129031105-5c2ff5dd-5bf6-4605-99a3-35d7c7c2b022.png)

Sorry if some words in the screenshots are difficult to read, it's Dutch in case you want to translate it.

**Comment by vic1707** [comment]
Hello, I've seen this issue, I'm currently on holidays so I have plenty of time to fix everything. 
It will be fixed today or tomorrow ( since I'm French our timezone should be close, so no conversion needed ^^)

**Comment by vic1707** [comment]
should be fixed with 83ed750.
