### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by Faizan2k7** [vic1707/AutoPlay-PokeMeow-Discord#2]
**Describe the bug**
It keeps doing the ;checklist function and does not proceed @vic1707 

**Screenshots**
![Screenshot 2021-03-13 134852](https://user-images.githubusercontent.com/80348254/111027711-fc24c000-8402-11eb-9dfc-e47c7bc7b92e.png)

**Desktop (please complete the following information):**
 - OS: Windows[e.g. Windows]
 - Browser firefox[e.g. chrome, safari]

**Additional context**

**Comment by vic1707** [comment]
Can I have a discord screenshot ? It looks like it didn't received any response from pokemeow

**Comment by Faizan2k7** [comment]
hmm k
![Screenshot 2021-03-13 150004](https://user-images.githubusercontent.com/80348254/111029255-d1d80000-840c-11eb-9bd3-422a3447f747.png)

**Comment by Faizan2k7** [comment]
over and over again like 5 times

**Comment by vic1707** [comment]
I Guess your -U isn't right... Should be
`-U "Faizan2007" `
Check it please ^^

**Comment by Faizan2k7** [comment]
ok lemme retry

**Comment by Faizan2k7** [comment]
its working tysm
