### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [name="email"]

### ISSUE THREAD

**Issue by jackson-hub** [vic1707/AutoPlay-PokeMeow-Discord#21]
So I kind of new to this and Im not really sure if this is a real bug or I am just not doing it right but I tried everything and anything I can to get it to work but it still shows the same error hopefully someone can be able to help me out with it.

OS: WIndows 10 Pro
Browser: Firefox Developer

![Screenshot_2](https://user-images.githubusercontent.com/85977438/131594056-68e5c3a6-34e0-4b68-b0ed-2639619d2198.png)
#21

**Comment by jackson-hub** [comment]
Upon running the py file it directed me here:
![Screenshot (224)](https://user-images.githubusercontent.com/85977438/131609212-d15289e8-e3c3-45d1-9491-a1cf9afbb6a1.png)

**Comment by vic1707** [comment]
You have to already be in the server with your account not invited.
Let the account you want to use be in the server, then get the direct link to the channel from a browser discord instance and use that link

**Comment by jackson-hub** [comment]
> You have to already be in the server with your account not invited.
> Let the account you want to use be in the server, then get the direct link to the channel from a browser discord instance and use that link

So do you mean I have to use an alt account to stay in the server to get the direct link and use it?

This is what I entered into the cmd: python bot.py -U 'xxx' -M 'xxxxxxxx@gmail.com' -P '(Password)' -C https://discord.gg/xxxxxxxx just in case if im doing it wrong

and does the bot work on the browser version of discord or the software or does it matter

**Comment by vic1707** [comment]
Yeah, the count the bot uses must already be in the server, from here you have to get the URL of the text channel you want it to spam/play.
The screenshot you sent here uses a url like discord.gg/invite
It must be discord.gg/channel
