### ISSUE TITLE
Looping checklist command

### ISSUE THREAD

**Issue by Kaiserzz** [vic1707/AutoPlay-PokeMeow-Discord#23]
Hello sir/mdm,  I was checking out your autoplay script recently and tried executing it.
However, i encountered an issue on firefox version 90.0.2 (64 bit) and the checklist command keeps looping and retrying. I did not see any errors on my command prompt / geckodriver logs.. It just keeps looping and retrying.
Could you advise me?

**Comment by Kaiserzz** [comment]
![image](https://user-images.githubusercontent.com/7664025/132899109-81d4bdd4-d7ee-4db0-b084-bd11f6f99c22.png)
On chrome, i see this error on my cmd prompt

**Comment by vic1707** [comment]
can you send the error log of the cmd prompt ? and explain the last thing you see on the chrome window before it crashes

**Comment by Melvin076** [comment]
I have the issue that it keeps looping on the daily stuff or hunt. any ideas?
I use firefox for it.
