### ISSUE TITLE
Browser immediately closes after running script

### ISSUE THREAD

**Issue by Sykkun** [vic1707/AutoPlay-PokeMeow-Discord#24]
**Describe the bug**
After following all the steps and running the program, it opens Firefox and logs in - but immediately crashes the browser afterwards. I have tried every single browser but the result is the same. Would love some help here!

**Screenshots**
![image](https://user-images.githubusercontent.com/91123552/134147910-43bf9d1c-20e9-4529-aef3-eeb2d3d52951.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Additional context**

**Comment by vic1707** [comment]
Try running the bot without the headless and tell me what you see before it crashes plz

**Comment by Sykkun** [comment]
I have never ran it with the headless mode. What happens is it opens Firefox, goes to discord - logs in successfully, then it crashes without even having time to show the channel.

**Comment by Sykkun** [comment]
I see nothing at all after the discord login, it always crashes in that same spot.

**Comment by vic1707** [comment]
it crashes during the loading time ? does it takes long to crash (~15sec)

**Comment by Sykkun** [comment]
When it is loading discord after logging in, it crashes. The total time to crash from the point I hit enter is around 15 seconds yes.

**Comment by vic1707** [comment]
ok so it's loading but never getting to discord, that's strange

**Comment by Sykkun** [comment]
Yes, it opens the browser, logs in discord then instantly crashes

**Comment by vic1707** [comment]
If it takes 15secs after logging to crash then it's not instant crash, those are differents ;-)
Anyway it seems like the bot after logging is unable to get to your channel, dunno why nor how to solve it, sorry

**Comment by Sykkun** [comment]
It instantly crashes after logging in to Discord is what I said :) Very different from a literal instant crash :-)

**Comment by Sykkun** [comment]
Useless dev

**Comment by vic1707** [comment]
You know that even if you've deleted the comment I still got the notif? Saying useless dev isn't really nice when I try to help you...
I simply try to understand what problem you encounter and simply can't really help you. 
Anyway hope insulting me solved your problem...
