### ISSUE TITLE
Error after ;items

### ISSUE THREAD

**Issue by thorvak** [vic1707/AutoPlay-PokeMeow-Discord#29]
It's 03:12:13, working time !
                         fore doing first task...
Traceback (most recent call last):
  File "D:\PokeMeow\bot.py", line 51, in <module>
    print(BAG)
  File "C:\Program Files\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 10-36: character maps to <undefined>

Press Enter to close !!

**Comment by vic1707** [comment]
looks like it can't decode a character, can you show me your username and or nickname on the server please?
