### ISSUE TITLE
Hi, this is just a suggestion

### ISSUE THREAD

**Issue by Faizan2k7** [vic1707/AutoPlay-PokeMeow-Discord#3]
Anyways you could code an image recognition system as the captcha for pokemeow is really annoying.This material might help.Sorry if im kinda annoying, especially for the pings @vic1707 
![20200626_140157](https://user-images.githubusercontent.com/80348254/111037114-c2b87880-8433-11eb-913b-f8205fb6552c.jpg)

**Comment by vic1707** [comment]
Yes I already have those, I started a branch to create a captcha solver. I'm for now able to clean the captcha by turning them to black and white but because I don't know anything about ML I can't do more for now.

Anyway thanks

**Comment by vic1707** [comment]
Just pushed each state of each number without visual pollution. May be usefull for ML...

**Comment by Faizan2k7** [comment]
hmm k
