### ISSUE TITLE
what is "AttributeError: 'CustomDriver' object has no attribute 'w3c' " meaning ?

### ISSUE THREAD

**Issue by neman0211** [vic1707/AutoPlay-PokeMeow-Discord#30]
what is "AttributeError: 'CustomDriver' object has no attribute 'w3c' " meaning ?

[New Text Document.txt](https://github.com/vic1707/AutoPlay-PokeMeow-Discord/files/7574266/New.Text.Document.txt)

**Comment by vic1707** [comment]
Dunno, can you show me the command you used to launch the bot? (hide your credentials)

**Comment by Geneticlord** [comment]
![image](https://user-images.githubusercontent.com/94822489/143387278-aa65c21c-1a47-4cd2-a029-b88e77963a8b.png)
I think this is the error he got

**Comment by vic1707** [comment]
Can I see the command used (with hidden credentials)? It would help

**Comment by vic1707** [comment]
Appears that we need to update the webdriver used by the bot (in the webdriver folder you have to change the provided file with an updated one corresponding to your version of the browser)
