### ISSUE TITLE
It only write ;checklist

### ISSUE THREAD

**Issue by xzxtheghostxzx** [vic1707/AutoPlay-PokeMeow-Discord#31]
after i run the bot it only write ;checklist for me i have read all the tutoriou but it doesnt work

**Comment by xzxtheghostxzx** [comment]
![image](https://user-images.githubusercontent.com/65434336/142812275-40eedb31-46ac-4191-8969-53866a5e6443.png)

**Comment by vic1707** [comment]
do you have a nickname that is different from your username (might be the issue)

**Comment by xzxtheghostxzx** [comment]
> do you have a nickname that is different from your username (might be the issue)

ok ill try that
