### ISSUE TITLE
Mac running bot error

### ISSUE THREAD

**Issue by mario2252** [vic1707/AutoPlay-PokeMeow-Discord#4]
Bot gives out error when trying to run, have installed requirements.txt file and also python 3.9. The bot will open the invite link but that's where it ends
![image](https://user-images.githubusercontent.com/80720003/111221017-332bda80-8597-11eb-9ac3-f08b01c6f578.png)

 - OS: Mac Big Sur 11.2.3 Mac Laptop using homebrew 3.9 python
 - Browser Opera and Firefox chrome won't even open

**Comment by vic1707** [comment]
As far as I can tell, it looks like it wasn't able To type your email in the field.
When not in headless mode, does it simply crash, can it input your mail ?

`Browser Opera and Firefox chrome won't even open `

Which one didn't even open ? Only Chrome, or is Firefox crashing too ?

Do all pip modules installé corectly ? 

I don't have my Mac on hand for now, I'll be able to take a look tomorrow around lunch time (around 12H from Now).

**Comment by vic1707** [comment]
And by invite link, do you mean à link to join a server ? Because that wouldn't be right

**Comment by mario2252** [comment]
> And by invite link, do you mean à link to join a server ? Because that wouldn't be right

Which link do I put?

**Comment by vic1707** [comment]
> > And by invite link, do you mean à link to join a server ? Because that wouldn't be right
> 
> Which link do I put?

It should be a direct link to a channel to a server where you're already a mermber of.

**Comment by mario2252** [comment]
> > > And by invite link, do you mean à link to join a server ? Because that wouldn't be right
> > 
> > 
> > Which link do I put?
> 
> It should be a direct link to a channel to a server where you're already a mermber of.

Got it working but seems to be looping on checklist any help?

**Comment by mario2252** [comment]
Keeps looping no idea why

**Comment by vic1707** [comment]
> Keeps looping no idea why fixed, lol now CL after every catch? No idea why, it was the name btw misread ty. Fixed that by completely eliminating checklist in the file no other solution and I do the cl anyways

shouldn't do it after every catch but after 20.
