### ISSUE TITLE
PokeGrinder for Slash Commands

### ISSUE THREAD

**Issue by MehulKhanna** [vic1707/AutoPlay-PokeMeow-Discord#44]
https://github.com/MehulKhanna/PokeGrinder

**Comment by vic1707** [comment]
Yeah?

**Comment by Mehul343** [comment]
> Yeah?

Yeah!

**Comment by MehulKhanna** [comment]
> Yeah?

Yeah

**Comment by vic1707** [comment]
What do you want from me ? Opening an issue and just posting a link...

**Comment by MehulKhanna** [comment]
> What do you want from me ? Opening an issue and just posting a link...

Nothing just put it here in case someone looking for a Pokemeow grinder for slash commands

**Comment by vic1707** [comment]
Do you realize how impolite it is to make an ad like that without any context, without any message, just by posting a link like that?
Simply asking politely for me to put the link somewhere easy to find would be more respectful and more helpful
