### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by tharun634** [vic1707/AutoPlay-PokeMeow-Discord#5]
**Describe the bug**
The bot just goes into a loop of typing `;checklist` until it says **MAX RECURSION REACHED** and stops

**Screenshots**
![image](https://user-images.githubusercontent.com/53267275/111737129-0e8c7700-88a5-11eb-93f5-0c23fee98417.png)

![image](https://user-images.githubusercontent.com/53267275/111737196-2bc14580-88a5-11eb-8449-68d6a8bcf041.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by tharun634** [comment]
okay, so I saw a similar issue #2 and then modified my command to run the bot, now I am getting a different error. 

![image](https://user-images.githubusercontent.com/53267275/111737886-68da0780-88a6-11eb-9bdb-2c0e722b2e40.png)

**Comment by tharun634** [comment]
ok, figured out that it's the character's in my username which is causing the error.

hardcoded my Username into the bot and it started to work

**Comment by vic1707** [comment]
for illegla characters you'll have to put backslashes before each of them `\`, I guess you'll have to do it before the two `=`

**Comment by tharun634** [comment]
ya, not issues, i hardcoded it now, but encountered a new bug

**Comment by vic1707** [comment]
> ya, no issues, I hardcoded it now but encountered a new bug

Yes I'm taking a look just now
