### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by tharun634** [vic1707/AutoPlay-PokeMeow-Discord#6]
**Describe the bug**
Infinite loop, runs `;swap` until **MAX RECURSION REACHED**

**Screenshots**
![image](https://user-images.githubusercontent.com/53267275/111738807-008c2580-88a8-11eb-9e52-b1435cebaff9.png)
![image](https://user-images.githubusercontent.com/53267275/111738823-071a9d00-88a8-11eb-8327-d26bfbe776d6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome

**Comment by tharun634** [comment]
it also loops with **;hunt** if I re-run the bot

![image](https://user-images.githubusercontent.com/53267275/111739084-77292300-88a8-11eb-8d30-e54c49d77cf0.png)

**Comment by vic1707** [comment]
Can you give me the result of your `;checklist` command please ?

**Comment by tharun634** [comment]
this was when it looped in `;swap`
![image](https://user-images.githubusercontent.com/53267275/111745258-582f8e80-88b2-11eb-8996-5e27a556084e.png)

this was when it looped in `;hunt`
![image](https://user-images.githubusercontent.com/53267275/111745304-68e00480-88b2-11eb-812e-827719622e9c.png)

**Comment by tharun634** [comment]
it's buying pokeballs in a loop too
![image](https://user-images.githubusercontent.com/53267275/111745451-9c229380-88b2-11eb-9da1-89c565cf7434.png)

**Comment by vic1707** [comment]
> it's buying pokeballs in a loop too
> ![image](https://user-images.githubusercontent.com/53267275/111745451-9c229380-88b2-11eb-9da1-89c565cf7434.png)

crap, this is because of your nickname, look at all the messages from PokeMeow, sometimes it calls you `tharun` and sometimes `-=EndlessGamer=-`

**Comment by vic1707** [comment]
as for your loop on `swap` and `hunt`, it's because the answer from PokeMeow isn't what the bot is waiting for (cf: My Screenshot).
But I don't know why it's not showing you the same as mine.... 
![image](https://user-images.githubusercontent.com/28602203/111748088-5ead0e80-8890-11eb-9541-4bccc24c9d0f.png)

**Comment by tharun634** [comment]
mistake was, i had a nick on the server, like how you pointed out. works when i removed my server nick
