### ISSUE TITLE
[SUGGESTION] buy pokeballs before ;pokemon

### ISSUE THREAD

**Issue by tharun634** [vic1707/AutoPlay-PokeMeow-Discord#7]
Can the bot check for balls inventory before it runs `;p` and buy if something is zero?

![image](https://user-images.githubusercontent.com/53267275/111899328-00c82480-8a52-11eb-8566-4a49e3d4104b.png)

As you can look in this image, the pokemon ran away, but it was common so, it wasn't an issue, what if it were a rarer pokemon that spawned.

**Comment by vic1707** [comment]
The I'm too poor message shows up when you don't have enought money to buy even pokeballs (even thought it shouldn't try to buy right after this message...)

Can you give me a little bit more history ? (of the discord messages as well as the output from the bot at this moment ?)

**Comment by vic1707** [comment]
And did it successfuly bought pokeballs after missing that pokemon ?

**Comment by tharun634** [comment]
> And did it successfuly bought pokeballs after missing that pokemon ?

Yes it did


> The I'm too poor message shows up when you don't have enought money to buy even pokeballs (even thought it shouldn't try to buy right after this message...)
> 
> Can you give me a little bit more history ? (of the discord messages as well as the output from the bot at this moment ?)

I do not have the bot output, I can provide discord output

You can see the coin balance in the images, to know that I did have enough money
![image](https://user-images.githubusercontent.com/53267275/111903336-d2554400-8a67-11eb-8a67-27f6bfccd4cd.png)


![image](https://user-images.githubusercontent.com/53267275/111903312-b3ef4880-8a67-11eb-9bb8-4455a664f88e.png)
Notice how it said `I am too poor`, even though I had the balance in the `shop` command
![image](https://user-images.githubusercontent.com/53267275/111903318-bd78b080-8a67-11eb-825d-3c759ce0d057.png)

**Comment by tharun634** [comment]
I got the screenshot in a new run of the bot 

![image](https://user-images.githubusercontent.com/53267275/111907891-2880b200-8a7d-11eb-8f86-d81374d90a69.png)
![image](https://user-images.githubusercontent.com/53267275/111907902-31718380-8a7d-11eb-95d3-a7d141f9528c.png)

**Comment by vic1707** [comment]
Found it, it happens when pokemons and fishes are enabled at the same time !

Form now it should be an easy fix

**Comment by vic1707** [comment]
fixed in #c088b77
