### ISSUE TITLE
only doing ;checklist?

### ISSUE THREAD

**Issue by hessedvrgn** [vic1707/AutoPlay-PokeMeow-Discord#8]
**Issue**
Is it just me being dumb or the bot is just doing ;checklist? (I'm not used to doing this type of stuff and I made it until here basically) I also tried it with -F argument and it still doesn't fish at all, please tell me if I'm missing something 

**Screenshots**
![image](https://user-images.githubusercontent.com/82619772/116746372-f88ade00-aa2e-11eb-91f3-c982fd6ccc66.png)

**Desktop**
 - OS: Windows 10
 - Browser Headless mode, but i used firefox too

**Comment by vic1707** [comment]
The bot always starts with checklist no matter what you ask it to do.
Maybe you have a nickname on this server/channel ?
Those are causing réal trouble because Pokemeow doesn't handle them really well.
Maybe some specials characters ?

**Comment by vic1707** [comment]
I understand you bluriing your pseudo, but unfortunatly it is most of the time the thing that make to bot go crazy
